### ISSUE TITLE
Preview pane stuck offset when copying large areas

### ISSUE THREAD

**Issue by TrazLander** [Khroki/MCEdit-Unified#251]
Copying a large, but within reason, sized area, makes the schematic preview pane stuck in an offset position:
![2015-01-02 04-38-38-am](https://cloud.githubusercontent.com/assets/4455904/5595168/b0e9a086-9239-11e4-9019-62f65fd330fe.png)

Copying smaller schematics only seems to suffer this issue for a split second, before fixing itself to the correct position after fully rendering itself.
![2015-01-02 04-38-57-am](https://cloud.githubusercontent.com/assets/4455904/5595180/e42ccf0e-9239-11e4-805c-3db10b539e46.png)
Big ones seem to get stuck even after fully-rendering the preview.

**Comment by OniOniOn-** [comment]
When Width or Length is over 272 blocks (starting from 273), this will happen.

**Comment by TrazLander** [comment]
Just confirmed that this issue started happening with commit https://github.com/Khroki/MCEdit-Unified/commit/efc7a22fd5f5a6686c13b3d035c42618de5ba7d3 which is the addition of pages to the copied schematics menu, done by @LaChal

**Comment by LaChal** [comment]
It happend before the implementation of the pages, as in MCEdit 1.1.0.1.

Look at the first item in the copy panel. You can see the gap on the left.
![capture du 2015-03-03 08 28 34](https://cloud.githubusercontent.com/assets/7809746/6458116/14b7c596-c180-11e4-8189-12d71e6a2161.png)
About 2.30 minutes elapsed between the two screenshots. And the preview is not complete.
![capture du 2015-03-03 08 31 02](https://cloud.githubusercontent.com/assets/7809746/6458140/6e779502-c180-11e4-9afa-e99746fde358.png)

This bug is due to the time to fully build the copied object preview and the lack of some check/update at the end of the build up.
