### ISSUE TITLE
Block Name Changes

### ISSUE THREAD

**Issue by MobileCrafter** [Khroki/MCEdit-Unified#270]
Wooden Doors are all named Wooden Door when you search them.
They should have tags like: (Top) (Bottom) (North) (West) etc.

**Comment by naor2013** [comment]
It seems like there are a lot of doors combinations:
15 possibilities for each door
7 doors (6 wooden doors and 1 iron door)

Which means there are 105 possibilities..
I'll add them tomorrow (I hope) so I'll assign it for myself, unless someone else wants to do that

**Comment by MobileCrafter** [comment]
Would be cool.
Thanks.

**Comment by Khroki** [comment]
Doors don't work that way, they are dynamically assigned positions based on the damage value of the bottom block combined with the top block, so it's not really possible to do what you're asking how mcedit works atm.

**Comment by TrazLander** [comment]
I added little extra info after every block with a data value to identify what they all mean, but during my progress I skipped doors...and never went back to them. The other one I skipped is fire...still not sure if I wanna do fire :P Ahh I can probably do fire no problem, I realized the 15 data values are all just part of a single int which determines its age. Which wall and face it's on is still only part of its blockstate. I'm bored enough I think I may redo the whole damn naming system to match their 1.9 block name system now since I have a big list of it.

**Comment by naor2013** [comment]
I'll do the doors, you'll do the rest
And I think you have issue to open you promised me for almost a week, so you've got stuff to do :P

**Comment by TrazLander** [comment]
psssh this is monotonous brain-dead work I can do. THAT requires me to think and problem solve :P

**Comment by TrazLander** [comment]
Updated doors in: https://github.com/Khroki/MCEdit-Unified/commit/2d889e41c5fbc2d5c189482c16174f19b4242d57

Also here's part 1: https://github.com/Khroki/MCEdit-Unified/commit/52ba65723cc7916df4c896d00674da7fc49573f0

**Comment by MobileCrafter** [comment]
Nice!
