### ISSUE TITLE
cant open

### ISSUE THREAD

**Issue by datking101** [Khroki/MCEdit-Unified#313]
having problem when i open it.. it says "running in fixed mode. support files are in your documents folder"

**Comment by Khroki** [comment]
What version? and does it just hang/close itself? or does it eventually throw an error?

**Comment by datking101** [comment]
It opens and hangs then closes





        Sent by Outlook for Android




On Sun, Feb 22, 2015 at 6:17 AM -0800, "Khroki" <notifications@github.com> wrote:
What version? and does it just hang/close itself? or does it eventually throw an error?

---

**Comment by datking101** [comment]
And it's the latest version





        Sent by Outlook for Android




On Sun, Feb 22, 2015 at 6:17 AM -0800, "Khroki" <notifications@github.com> wrote:
What version? and does it just hang/close itself? or does it eventually throw an error?

---

**Comment by Khroki** [comment]
If it just closes, could you try the following:
1. Open the command prompt
2. Type [cd ] (no brackets, note the space), then drag the folder mcedit.exe is in onto the command prompt window to make [cd "mcedit\folder\name\here\"]
3. Press enter
4. Drag mcedit.exe into the command prompt window
5. Press enter
Then let us know the error instead of closing.

**Comment by Coreavus** [comment]
I have this same problem. Program starts to open...shows splash screen like it's about to start then just closes. I did the suggested actions and here is what the command prompt gave me:

C:\Users\****>cd C:\Users\****\Downloads\MCEdit.v1.3.0.0.Win.64bit\mcedit

C:\Users\****\Downloads\MCEdit.v1.3.0.0.Win.64bit\mcedit>C:\Users\****\Downloa
ds\MCEdit.v1.3.0.0.Win.64bit\mcedit\mcedit.exe
Splash load...
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Kris\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_importe
rs.py", line 276, in load_module
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\version_utils", line 249, in <
module>
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\version_utils", line 69, in __
init__
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\version_utils", line 41, in __
convert
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: u'C:\\Users\\****\\Documents\\MCEdit\\usercache.json'

**Comment by naor2013** [comment]
After a little research, this bug is a Windows-only bug where broken usercache files can't update..
For now, you can delete the usercache.json file yourself and it will be fixed but I'm sure Podshot can fix this..

**Comment by Coreavus** [comment]
Perfect...that worked! Thanks
