### ISSUE TITLE
Upcoming 1.4.0.0 release

### ISSUE THREAD

**Issue by TrazLander** [Khroki/MCEdit-Unified#436]
Calling all the major players, plus some others that might be bored and want to help.
@Khroki @naor2013 @LaChal @Podshot @Rubisk @ezfe @martinhanzik @freundTech @OniOniOn- @skinny121 @DragonQuiz @Iciciliser @Curly- @codewarrior0 

1.4.0.0 is the Pocket Edition update, and it's on its way to being finalized.

*I have gone over every issue report, cleaned them up, re-prioritized them, and made a list of what needs to be done to finish 1.4.0.0.*
At the top of this doc. https://docs.google.com/document/d/1YpX-ORVrUSf3L1sutn5nuSeOLbaQZJYYrza4fBsw8Y8/edit?usp=sharing

Preview:
![screenshot 2015-07-08 06 22 30](https://cloud.githubusercontent.com/assets/4455904/8568209/c29bc14a-2539-11e5-9743-7bbfe633cf36.png)

At the time of me typing this, there's about 12 issues left. Feel free to pick one out, and take a crack at clearing it off of there! @Rubisk has mainly doing a lot this last bit himself, and could use any support that can be provided. I added some that may not seem to priority, but should be easy enough quick-fixes.

Feel free to submit any final issues, or add any minor features that are not on the final list. But when that list is empty, it will be released!

P.S. The @threetwo feature requests are *optional*, but I'm adding them there anyway since he's a bro.

Thank you everyone for your support!

**Comment by OniOniOn-** [comment]
Can you send me a MCEdit dev version compiled and minecraft debug world? I need to check block ids. (I really can't even run MC)

**Comment by LaChal** [comment]
* Filter - MCEdit-Unified/#433 Filter translations are broken: fixed in https://github.com/Khroki/MCEdit-Unified/commit/3bd79b5b05da0e29aa1dfa05d51af2d612300899.
* Language - Toggling language, hitting Cancel -> Don’t Save, will toggle you back to your langauge, but sometimes still keep the new language’s font: examples: http://i.imgur.com/spfdzF1.png http://i.imgur.com/Q1WJEQc.png: fixed in https://github.com/Khroki/MCEdit-Unified/commit/19adb84ab2c7e52920fecba6580659b7ffb5332e.  
  

* Translations - Find a way of hacking translation in and/or redo albow.translate: ???

**Comment by Rubisk** [comment]
Thanks, @dens for fixing what i broke :/. That final one meant: setup albow.translate to not depend on reimporting.

**Comment by OniOniOn-** [comment]
This issue really needs to be renamed. It makes me think 1.4.0.0 is released everytime I see this.

**Comment by LaChal** [comment]
@Rubisk: no problem :p
Concerning the reimport of the translation functions, I've searched a way to set them up, but the only option I can see is to inject them in the filters code at runtime. So, each filter handles its own translation in its own 'namespace'. And we don't 'polute' MCEdit ones.
To have the injection to work, it is necessary to remove `albow.translate` from `sys.modules`, and reimport it after the filter translation is loaded. This is due to the fact that python does not realy create a copy of an already imorted module when using `import foo as bar`.  

As I said, I explored other ways, like using `imp` to try to load a copy of the module, but it'll work only when running from source. I guess it can work on 'frozen' forms, but we'll have to distribute a copy of the file and tweak horribly the code to make MCEdit find it.  

Other ways (I did not explored) may work. But it is important to keep the code simple and fast.
We can encapsulate the translation fuctions into a class, but it may be more time consuming and will take more memory room. And it may not solve the injection in the filters code...  

By the way, I'm currently on a new job and have moved few weeks ago. I've less time...
And I'm also working on another project concerning automated tests about installing stuff on different Linux distributions. I hope it'll be soon finished, since it will help to distribute MCEdit :)

**Comment by Rubisk** [comment]
Wow. That looks a lot cleaner indeed, thanks :-)

**Comment by OniOniOn-** [comment]
Is there any bug left that is preventing 1.4.0.0 release?

**Comment by TrazLander** [comment]
none are crashes, so not really

**Comment by LaChal** [comment]
Right, but some things are broken since the 1.3.3.0.
It may be a good idea to repair them.

**Comment by TrazLander** [comment]
but also maybe good idea to release if no one has any time to do them

**Comment by OniOniOn-** [comment]
Ok, so it is upcoming. Then, let's release it today!

**Comment by Khroki** [comment]
We'll release when the bugs are sorted, for example rotations involving doors cause errors and the forester filter is broken.

**Comment by LaChal** [comment]
And translators will have a bit of work before the release...

**Comment by Khroki** [comment]
Technically this is resolved. Make a new issue if something comes up.

**Comment by ezfe** [comment]
Thanks for keeping me in the loop on these, I appreciate the @ mentions @TrazLander
