### ISSUE TITLE
MCPE chunk blocks are stored as a uint8. This should be a uint16

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#462]
Not major just an odd bug I just found it odd. I stumbled across this when messing around with the snapshot. I made a quick filter to fill an area with block ids dependant on location to find new ids and stumbled across it. 

Ids 256, 512, 768 (and I presume continuing but I have not tested further) are rendered as fully transparent but can still be clicked on and selected as if they were there. Everything around has the standard unknown texture.

As always. Love the program and love you guys for continuing to develop it

**Comment by skinny121** [comment]
Within your filter how exactly are you setting the blocks?

I cannot reproduce by setting the blocks using the fill tool, they appear as future blocks as expected. Also 
can you select the block and press 0 and tell me the ID(should be on the second row).

**Comment by gentlegiantJGC** [comment]
I used the level.setBlockAt method and level.setBlockDataAt. x is the value of the id and z is the damage value.

256:0-15
512:0-15
768:0-15

Just tested and this isn't dependant on the location of the block. I also noticed it in the last version so it has not come about in the latest version

Just tested with the fill tool and they appear transparent using that method as well

**Comment by Rubisk** [comment]
The issue is that blocks in the Pocket Edition are apparently stored as a uint8, instead of a uint16, which it should be. Looking at it now I'm surprised there's not more that breaks.

Anyway, anything block above 255 will be converted to a number 0-255. 256:0 is written to the chunk as 0:0, which is air. MCEdit just writes air to the chunk. Everything is fine in the preview rendering etc.

The bad code can be found at https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/leveldbpocket.py#L1004

I'll get around to fixing this once I move all the worlds to one world format. I'm not very good with this kinda stuff, and I can't seem to figure out quickly how exactly I should read and store the data as a uint16.

Expect a fix in the next one or two releases, I'd say.

**Comment by skinny121** [comment]
Finally was able to reproduce this issue. It only occurs if hidden ores option is turned on, it is fixed know.

@Rubisk thats an unrelated issue as @gentlegiantJGC was using a pc world, that probably should be in another issue.

**Comment by Rubisk** [comment]
I actually couldn't reproduce on pc world,  so I opened PE and reproduced something a lot like it.
