### ISSUE TITLE
2 strings in "New Waypoint" have wrong offset after translation

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#511]
They are "Waypoint Name" and "Save rotation", the last 2 strings in the translation file.
After being translated, they move to upper left a bit. When both of them are translated, only the former one is in wrong position. Pictures are below:
![1](https://cloud.githubusercontent.com/assets/11222265/10278258/61d95e62-6b8e-11e5-9f8d-44f6862aff91.png)
![2](https://cloud.githubusercontent.com/assets/11222265/10278257/61c6489a-6b8e-11e5-9023-b488f50e135f.png)
![3](https://cloud.githubusercontent.com/assets/11222265/10278260/6210bb96-6b8e-11e5-8274-3093cb6cb7c0.png)

Haven't tested if it happens in ASCII languages

**Comment by LaChal** [comment]
It does not happen on Linux and XP with french translation. But I confirm it happens on both Linux and XP with the simplified chinese translation.
  
Not sur of the cause yet. It can be related to the font or, more probably, to the layout of the components in the widget.

**Comment by LaChal** [comment]
Hummm...
  
This bug is due to the fact there's an unwanted trailing new line at the end of the translation file.
  
Please, just remember that the .trn files obey to a simple but strict formatting. Any character is important: letters/ideogram, symbols, spaces, tabulations and blank lines are caught by the translation functions and transmitted to the GUI.
Consider to keep under your hand the ['TRANSLATION.txt'](https://github.com/Khroki/MCEdit-Unified/blob/master/TRANSLATION.txt) file.
Please, let me know if the explanation in this file isn't clear. I'll update it :)
  
(By the way, I can be blamed; because I did not noticed this before...)

**Comment by fhfuih** [comment]
Oh I get it. My Atom Editor creates a trailing whenever I save the file. It is ... somewhat ... annoying.
