### ISSUE TITLE
Filling Trapped Chests locks them

### ISSUE THREAD

**Issue by MaxMatti** [Khroki/MCEdit-Unified#527]
The title basically says it: in MCEdit when using the fill tool (hotbar slot 4) to fill a selection with trapped chests (in my specific case replacing stone with trapped chests) makes them inaccessible to the player after saving the world and opening it in Minecraft.

Minecraft: 1.8 with Forge+Liteloader
MCEdit: window-title says "Unified v1.4.0.1 for Minecraft 1.8/1.9"
OS: Linux Mint 17.1 Rebecca, Kernel: 3.13.0-37-generic

**Comment by LaChal** [comment]
There's an error in the data for the trapped chests.

Editing it's NBT data and changing the id to `Chest` (instead of `Trap`) makes the trapped chests accessible in game. <a name="from_1" href="https://github.com/Khroki/MCEdit-Unified/issues/527#to_1">(1)</a>

This will be fixed in the next release.
<br><br><hr><a name="to_1" href="https://github.com/Khroki/MCEdit-Unified/issues/527#from_1">(1)</a> Place trapped chests with any method you want. Select the aera where you placed the chests. Then select the NBTEdit filter and search for `TileEntities` in the selected aera. In the results panel, deploy each element and change the `id` tag to `Chest`.
