### ISSUE TITLE
MCEdit crashes while start

### ISSUE THREAD

**Issue by AZm87** [Khroki/MCEdit-Unified#536]
when I want to start MCEdit, it crashes after Splash load...

[log.txt](https://github.com/Khroki/MCEdit-Unified/files/44253/log.txt)

**Comment by LaChal** [comment]
The message says that a part of MCEdit is missing.

Please, verify if there's an `Items` folder in your MCEdit install. If not, you'll have to reinstall the program.

It may also be due to the fact you call the program from another folder than where it is.

Try `mcedit.exe C:\Map\level.dat` from MCEdit folder.

**Comment by Khroki** [comment]
Ah, this is because you didn't CD to the MCEdit directory to run it, it doesn't work being called from another folder, you have C:\Map>"C:\Program Files\Tools\mcedit\mcedit.exe" level.dat, you should try
CD "C:\Program Files\Tools\mcedit"
mcedit.exe C:\map\level.dat

The reason behind this is some of MCEdit runs off relative directories, so if your working directory is elsewhere it'll look in C:\map\Items instead of C:\Program Files\Tools\mcedit\Items
Let us know if this doesn't work. You can also make a batch file to help if you have a really long map name. You can also try a shortcut with parameters if you like, this is untested though.

**Comment by Khroki** [comment]
Let us know and reopen this if it still doesn't work.
