### ISSUE TITLE
Linux version MD5 mismatch for MCEdit.v1.5.1.0.Lin.Universal.run

### ISSUE THREAD

**Issue by Xavom** [Khroki/MCEdit-Unified#603]
Linux version MD5 mismatch for MCEdit.v1.5.1.0.Lin.Universal.run :
3c3088a77a2ed44678c6a43c381e4f62 MCEdit.v1.5.1.0.Lin.Universal.run
I have downloaded and checked the last 3 versions for Linux and all of the MD5 hashes are different from those on the download page.

**Comment by Khroki** [comment]
Hmm, dens does the hashes on the linux builds when he creates them, maybe he knows what's going on. I did notice an older release hashed differently on my machine but didn't think much of it.

**Comment by Xavom** [comment]
Well let's hope this issue does not get closed as a duplicate as the last issue did 19 days ago.

**Comment by Khroki** [comment]
What issue would that be? The only ones I've closed for being duplicates had near identical issues already on the tracker.

**Comment by Xavom** [comment]
That would be #588, marked as closed duplicate.  I can't seem to find an open issue with this topic, so I created another since it seems to be unresolved.

I am moving away from the unsecure Windows OS for my everyday computing and Linux has that covered along with much more security.  An MD5 checksum mismatch is a real issue to us Linux users.

**Comment by LaChal** [comment]
MD5 (or other hashes) are used only to verify packages integrity.
The fact is MCEdit is not installable as a distro package, and the MD5 is given for information.

By the way the one given is not wrong. It is the one issued while packaging the `.run` data, not the `.run` itself.

#588 is closed because resolved. Also closing this one.
The actual MD5 will remain as is. The future ones will reflect the `.run` hash.

**Comment by Khroki** [comment]
For now I can tell you the correct package hash is 3c3088a77a2ed44678c6a43c381e4f62

**Comment by LaChal** [comment]
OK.
I got the same hash on my side, and just noticed the 'Edit' button on the release page...
