### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Clouds-To-Write** [Khroki/MCEdit-Unified#661]
Caught this error when tried to open my server world. Any suggestions? #
![43](https://cloud.githubusercontent.com/assets/19241450/15093297/ea783922-148b-11e6-9f51-e865b2e8d620.PNG)
![44](https://cloud.githubusercontent.com/assets/19241450/15093322/0604cca4-148d-11e6-8300-e2f9c79c2b8b.PNG)

**Comment by LaChal** [comment]
Hmmm...
The UI show an UnicodeError, but the console shows something else.

Do you use non-english characters in MCEdit?
Do the two errors happend at the same time?

The console screenshot (second one) is not complete. Can you send us the whole output?
Alongside MCEdit itself (`mcedit.exe`), there shall be a a `mcedit.log` file. Please, join it. It can contain usefull information.

**Comment by robske110** [comment]
Why does MCEdit actually have so many text encoding problems? Is phyton generally known for that?

**Comment by Khroki** [comment]
It's the combination of python 2.7, windows, and pyinstaller 2.1. The thing is python wants to access directories using ascii under windows so attempts to use UTF8 characters just goes out of range and breaks everything. We're still looking into fixes.

**Comment by violine1101** [comment]
This issue occurs for me when starting MCEdit 1.5.2.1 while using a language such as German and MCEdit tries to load the "für" in the window title from the translation file. Also, when analyzing a selection, MCEdit cannot export the analysis it when the language is set to German because it has problems with unicode characters there as well.

**Comment by LaChal** [comment]
@violine1101 
The error concerning the non-ANSI characters in the window title is fixed for the next release. You can easily fix it yourself by editing the German translation file and changing the translated string #949 (around line 2041, the `t949 für` one). Don't remove the line, just change the word.
Concerning the analysis save bug, I don't experience it on my side.
Your log file will help :wink:

@Clouds-To-Write 
The error you reported in you second screenshot seem to be due to invalid data in a part of your save (a player file).
MCEdit displays this error because it is not able to display a message correctly in Windows shell (which does not support every character sets).

Look in the save folder. There shall be a `players` folder containing `.dat` files.
Move the ones which contain non English characters.

A fix will be added in the next release. It shall only fix the unicode error, not the wrong data in the files.

Please, once the release is out and you got it, report here, even if it is fixed. (Especially if it is fixed :smile:)

**Comment by Khroki** [comment]
Could you test the latest release?

**Comment by violine1101** [comment]
When trying to analyze a selection when language is German, it says
> Error during <function analyzeSection at 0x000000000A24D198>: UnicodeEncodeError('ascii', u'Wasser (Still, H\xf6he 6)', 16, 17, 'ordinal not in range(128)').

Console output:
```
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
  File "editortools\select.py", line 1162, in analyzeSelection
  File "leveleditor.py", line 811, in analyzeBox
  File "albow\widget.py", line 546, in present
  File "albow\root.py", line 303, in run_modal
  File "albow\widget.py", line 400, in handle_mouse
  File "albow\widget.py", line 482, in call_handler
  File "albow\controls.py", line 240, in mouse_up
  File "albow\widget.py", line 482, in call_handler
  File "leveleditor.py", line 789, in saveToFile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 16: ordinal not in range(128)
```
MCEdit 1.5.3.0

**Comment by LaChal** [comment]
This error does not happen when analysing, but when saving data to file right?

**Comment by violine1101** [comment]
Yes, that's what I meant with 'export'.

**Comment by LaChal** [comment]
For now, you can export using English to export the analyse result.
The output format is CSV.
