### ISSUE TITLE
Suggestion for McPe

### ISSUE THREAD

**Issue by hdjackill** [Khroki/MCEdit-Unified#668]
Maybe MCPE might work better if you add a way to generate MCPE terrain in McEdit, it may even help you solve some problems since it may give you a better understanding of how MCPE works.

**Comment by Khroki** [comment]
Well, we generate Minecraft terrain by starting the actual Minecraft server and copying the chunks over, this approach is a bit unrealistic for pocket since it doesn't run natively on any desktop OS so it's extremely unlikely we'll do this unless someone wants to port the generator over, which is both difficult and would require tweaking for every new version.

So yeah, sorry, good idea but not realistic for us.

**Comment by hdjackill** [comment]
Pocket as same terrain generation system as the Windows 10 version of minecraft so it kinda does

**Comment by Khroki** [comment]
Neither pocket nor the Windows 10 edition have separate server software, which is how we currently generate land. and by new version I mean .11, .12 .13, .14, etc.
