### ISSUE TITLE
Many Errors in Kali Linux

### ISSUE THREAD

**Issue by bgbrandongomez** [Khroki/MCEdit-Unified#706]
Hello, this bug report is for Kali Linux as I mentioned I would create a bug report in issue #694 in [this comment](https://github.com/Khroki/MCEdit-Unified/issues/694#issuecomment-237239329).

For Kali Linux, the first issue I noticed is the installer v1.5.3.0 does not detect setuptools. I have python-setuptools (version 20.10.1-1.1) installed. I also have python3-setuptools (version 20.10.1-1.1) installed.

The only dependencies that may be having issues are

> * Libraries found but must be dowgraded:
>  - numpy is 1rc1.1.11, should be at least 1.8.1.
>  - pygame is 1.9.2, should be 1.9.1.

and I had to install the other dependencies manually due to setuptools not being detected.

The NBT Support tests results are

> Some tests failed. The error code is 256.
The output is:
> *** Starting NBT tests...
> *** '_nbt.so' imported successfully.
> *** Calling testCreate.
> *** Calling testErrors.
> *** Calling testList.
> *** Calling testLoad.
> MinecraftLevel
> 23
> [7 7 7 ..., 0 0 0]
> *** Calling testLoadNBTExplorer.
> *** Calling testLoadUncompressed.
> *** Calling testModify.
> *** Calling testMultipleCompound.
> *** Calling testSpeed.
>     testSpeed failed:
> [Errno 21] Is a directory: 'testfiles/TileTicks_chunks/c.0.2'
> *** Calling testToStrings.

The Pocket Edition Support Tests results are

> An error occured when runnig the test:
> Traceback (most recent call last):
>   File "test.py", line 2, in <module>
>     from leveldb_mcpe import DB, Options, ReadOptions, WriteOptions, WriteBatch, RepairWrapper
> ImportError: libleveldb.so.1: cannot open shared object file: No such file or directory
> 
> Hit ENTER to continue.
> * * * cwd: /home/senor/Downloads/mcedit/leveldb_mcpe
>       cur_dir: /home/senor/Downloads/mcedit
>       os.path.join(cur_dir, 'leveldb_mcpe'): /home/senor/Downloads/mcedit/leveldb_mcpe
>        True
> Building Linux application 'leveldb_mcpe'...
> ls: cannot access 'build/*/leveldb_mcpe.so': No such file or directory
> The library is already present. Do you want to recompile [y/N]?

I selected no to rebuilding both libraries (NBT and Pocket Edition). I am still in the process of debugging it on my end. Thank you for your help!

**Comment by LaChal** [comment]
Thank you for the feedback.

Actually, the NBT test failure on 'testSpeed' does not prevent the .so to work.

The setup tools not found issue has already been reported, and will be fixed in the next release.
I guess if you invoke `easy_install --help` in a shell, you will see a reference to Python 2.7 in the docstring for the parameter '--user'.
By creating a symbolic link somewhere in your $PATH -- called `easy_install-2.7` and pointing to the one reporting the Python 2.7 ref -- you'll solve this part.

I suggest you to create the symbolic link and retry (but since you installed the dependencies, the installer will not try to reinstall them, so you may uninstall a Python lib you know you installed for MCEdit before).

I'm looking to the PE support part, but can you tell me if yo tried to test/build it manually?

**Comment by bgbrandongomez** [comment]
As for the PE support part, I had copied the terminal output to https://pastebin.com/Rfk9na7X. For Setup Tools, the directory I got for easy_install-2.7 is /home/senor/.local/lib/python2.7/site-packages. It is a blank directory. It did not help the installer find Setup Tools. I had mapped it to /home/senor/bin/ which is in $PATH.

**Comment by LaChal** [comment]
Your log says Mojang's sources can't be found.
The file `leveldb_mcpe/setup.py` contains a bad reference to Mojang's sources... (The fact is the file is a bit old the Linux part in this file is, hmmm, not maintained.)
Try `leveldb_mcpe/setupnx.py build` instead. It will check some dependencies, then build the stuff.

**Comment by bgbrandongomez** [comment]
The setupnx.py test output http://pastebin.com/khERCzRX. It seems to have the same error.

**Comment by LaChal** [comment]
Hmmm...
I see the change concerning Mojang's source has been pushed after the release, so, no luck with this.

You can edit the script and change the line 289 for:
```
        os.system("""wget -O leveldb-mcpe-master.zip https://codeload.github.com/Mojang/leveldb-mcpe/zip/a056ea7c18dfd7b806d6d693726ce79d75543904""")
```
This is the line right after the `# Retrieve Mojang resource linked in MCEdit sources. I know, freaking command line :p` one. Pay attention to preserve the 8 leading spaces, or you'll get other errors.

**Comment by bgbrandongomez** [comment]
Well, I changed the line and it looks like the error has to do with a missing .so. https://pastebin.com/7vmb1QDB contains the log.

**Comment by LaChal** [comment]
Look at the file `LINUX_INSTALL.txt` (which is generated in the directory `mcedit` at start of the installer). The 'POCKET EDITION SUPPORT COMPILATION' section. It describe how to fix an 'undefined symbol' error.
Note it may not apply exactly to the error yo get.

**Comment by LaChal** [comment]
@bgbrandongomez 
A new release is available here: http://www.mcedit-unified.net/

The first error you reported here (PE support test failing) was due to a bad symlink creation.
The setuptools detection has been improved.
The Mojang's sources bug has also been fixed.

My advice is to install this release, and see what happens :smile:
It won't override your former MCEdit version, except the .so symlinks (in `~/.local/lib`), and the launchers (if you choose to create them during installation).
The directory where the program will be installed is called `mcedit-1.5.4.0`.

Just reopen this issue if you still experience issues with the PE support :wink:
