### ISSUE TITLE
Camera viewport can capture mouse while modal dialog is active

### ISSUE THREAD

**Issue by nomadictype** [Khroki/MCEdit-Unified#724]
MCEdit version: 1.5.4.1 (commit d6d125f3713c6aced5cdc9fda00a6833939a8e5b)
MC version: 1.8.1
Python 2.7.10
pygame 1.9.2b8
Gentoo Linux, XFCE4 with xfwm4 window manager

**Steps to reproduce:**
* Load a level, find or place a block that opens a modal dialog when double-clicked (e.g. sign or chest)
* Hold right mouse button to capture the mouse for camera control
* Double-click the aforementioned block to open the modal dialog. Keep the right mouse button pressed still
* Move the mouse cursor outside the modal dialog
* Release the right mouse button

**Expected result:**
* Nothing. The camera viewport shouldn't be able to capture the mouse while a modal dialog is open.

**Actual result:**
* The camera viewport captures the mouse. At this point MCEdit essentially becomes unusable. The mouse cursor is hidden and even though it can be moved, button presses do nothing, so the modal dialog can't even be closed. The only solution seems to be to quit MCEdit (which is actually difficult while the mouse is captured; one option is to kill the process from another user's session, another option is to press F6 to open the screenshot dialog, which releases the mouse temporarily, and close the MCEdit window).

Although the last few reproduction steps might seem a bit convoluted, it's quite easy (for me at least) to trigger this bug unintentionally. This causes me to have to restart MCEdit often.

EDIT: Found a potential fix: #725.

**Comment by LaChal** [comment]
I can't reproduce this on my side on Ubuntu (Gnome and Unity environments).
Mint 17.2 (Cinnamon desktop) does not have this behaviour, nor openSuSE 13.2 (KDE).

Note that we have a support for moving/resizing MCEdit window on *some* Linux desktop environments (Cinnamon, Unity, Gnome and KDE), but XFCE4 is not yet implemented. (I need room on my machine for that...) The console shall display the message: `Your desktop environment is not yet supported for window sizing/moving.`
Also, the ideal pygame version for MCEdit is 1.9.1. Later versions *may* work.

IMO, the behaviour shall be not opening the widget when the camera control is requested, since the camera control came first in the event queue.

Anyway, thank you for the report (and the fix proposal) :smile:
