### ISSUE TITLE
Can't save schmaticisized worlds

### ISSUE THREAD

**Issue by gmbr3** [Khroki/MCEdit-Unified#756]
You can't save schmaticisized world.
You recieve error; 
Error during <function saveAs at 0x000000000A39ED68>:
AttributeError("'MCSchematic' object has no attribute 'worldFolder"',)

**Comment by LaChal** [comment]
I guess you exported a full world to a schematic file and want to convert this schematic back to a world.

Opening a schematic and saving it as a world as is does not work because no chunks are present in the schematic file.
Schematics are not intended to be complete worlds, but strcutures/data to be imported in existing worlds.

To convert schematics in MC worlds, the method is:

1. Open your schematic and select all the blocks (`Ctrl-A`).
2. Get the chunk size by dividing the selection width and length by 16, rounded to the upper.  
Example: If your schematic is 4855W x 48314L x 256H, the 'chunk size' will be (4855 /16) x (48314 / 16) = 304 x 3020.
3. Create a new world with the above calculated chunk size.
4. Select all the blocks in this world and delete them. Pay attention to not delete the chunks, only the blocks!
5. Delete also entities and tile ticks.
6. Import your schematic and place it as you want. Pay attention it's not beyond of the chunks edges.  
You'll certainly have to switch from the camera view to the chunks one several times.  
My advice is to import the schematic in chunk view and to check all the boxes in the panel to ensure that water, air and biomes are copied, and that all the coordinates and UUIDs are refreshed. Checking the `Chunk Align` one may help also.
7. Save your new world!
