### ISSUE TITLE
Memory errors when exporting

### ISSUE THREAD

**Issue by malonnnn** [Khroki/MCEdit-Unified#776]
Edit:
I just realized my included pictures also include my 2nd monitor which was playing MC at the time...please ignore the MC screenshots

**The Issue:**
I'm getting memory errors when trying to do a large export (specifically Broville)
Everything works fine until the dialog box asking me where i want to save the .schematic file pops up

**System Specs:**
8GB RAM
Broville map ver 1.11.1
MCEdit-Unified v1.5.6.0 for Minecraft 1.8-1.11.2
Windows 8.1 x64 
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Evidence (RAM column is sorted DESC by usage):**

- My system before export
- http://i.imgur.com/v8K1ecL.png

- My system at the beginning of export
- http://i.imgur.com/L1DQeUG.png

- My system halfway through export
- http://i.imgur.com/l56Bj6N.png

- The Error (pops up as soon as .schematic save dialog appears)
- http://i.imgur.com/dS0Z6FH.png

**Conclusion:**
As far as I can tell, based on the memory usage, I don't believe i'm running out of memory, so that's why I'm reporting this as a bug.

**Comment by EmanYm** [comment]
Unrelated to your issue, but will help with future screenshots.  Try Gyazo.com

**Comment by LaChal** [comment]
According to your last screenshot, it looks like you used the NBT structure format for the export.

Can you retry with the schematic format by selecting it in the file chooser when exporting?

**Comment by malonnnn** [comment]
@LaChal 

You appear to be correct. I click the "Export" button (the hover tooltip says "Export selection to a .schematic file" but when the save dialog appears, the file extension ends in .nbt - how do I select .schematic or .nbt?

I made a video of the entire process here
https://www.twitch.tv/videos/134797749

**Comment by naor2013** [comment]
Well, for some reason it saves all of the blocks in RAM which is weird and impossible with big maps... We'll need to find a way around it and using storage rather than RAM if it's possible...

**Comment by LaChal** [comment]
Thank you for the video :smile:

When the save dialogue pops, select the schematic file format in the 'Save as type' drop-down list
Just pay attention the file extension is changed for `.schematic` instead of `.nbt`

Please note that MCEdit 1.5.6.0 can't reimport these large schematics. The game can't manage them too.

Regarding MCEdit, there is a work around (fix is implemented for the next release):
* Open the schematic with an archive manager which handles zip files.
* Rename the `##MCEDIT.TEMP##` folder to `region`. If renaming inside the archive is not possible, extract it, rename the folder, rezip and change the extension for `.schematic`.

Also, note that you may have missing chunks in the schematic. (I saw this issue on my side, badly still no fix :/)

**Comment by malonnnn** [comment]
@LaChal 

My ultimate goal was to merge two very large worlds.

Do you know of a way to do this if McEdit is unable?

**Comment by LaChal** [comment]
A solution exists, which is to merge two worlds.

Click on the import tool, and select the `level.dat` file in the world folder :smile:

Kudos to  abrighmoore: https://www.reddit.com/r/MCEdit/comments/60bdr5/would_someone_please_help_me_make_a_schematic_of/dgg1vpf/
