### ISSUE TITLE
NameError: global name 'Xlib' is not defined

### ISSUE THREAD

**Issue by SeafoxWeb** [Khroki/MCEdit-Unified#797]
Starting MCEdit...
Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.6.0
[ WARNING][            mcplatform.py:1276]:Initializing window management...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/chris/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
mcedit.main MCEdit exited with errors.
[   ERROR][                  root.py:1049]:MCEdit version Unified v1.5.6.0 %s Minecraft 1.8-1.11.2 | PE 0.11
Traceback (most recent call last):
  File "/tmp/release-master/MCEdit-Unified/__main__.py", line 42, in <module>
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 1046, in main
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 772, in main
  File "/tmp/release-master/MCEdit-Unified/utilities/gl_display_context.py", line 25, in __init__
  File "/tmp/release-master/MCEdit-Unified/utilities/gl_display_context.py", line 65, in reset
  File "/tmp/release-master/MCEdit-Unified/mcplatform.py", line 842, in __init__
NameError: global name 'Xlib' is not defined

==================================
			  MCEdit has crashed
==================================
Press the Enter key to close this window

**Comment by LaChal** [comment]
The Python Package Xlib is needed on Linux.

Run the installer and let it install the library, or install it yourself. The version 0.14 is the minimum one required.

**Comment by SeafoxWeb** [comment]
When I run the installer, it seems to not locate the python-xlib sorry I feel stupid for asking, but how exactly do I install it myself?

**Comment by SeafoxWeb** [comment]
Also not sure if relevant but upon running install.sh i get this:
`
Traceback (most recent call last):
  File "../bin3/mcedit-1.5.6.0/install.py", line 1133, in <module>
TypeError: coercing to Unicode: need string or buffer, bool found
`

**Comment by SeafoxWeb** [comment]
Have now fixed it, by updating numpy:
`pip install --update numpy`
p.s. I needed sudo to write to the directory.

**Comment by LaChal** [comment]
Right, by default pip installs the libraries system wide, which requires root elevation.

To avoid trouble with the dependencies, I recommend you to run the installer.
Even if you want to install the dependencies yourself (and at the moment, some dependencies like numpy and pygame need root elevation, hope it'll be fixed in a future version of the installer...), let the installer check them.
You'll get a list of what is installed, not installed, compliant or not.

The `easy_install` utility (part of `setuptools`, AKA `python-setuptools`) let you install Python packages in a custom place. You can use it to avoid system breakage :smile:

Also, there are some note about installing MCEdit-Unified on linux included in the installer. These notes are displayed right after the disclaimer.

**Comment by af001** [comment]
I was able to resolve using:
`pip install xlib`

Also note that the current release of ftputil (currently v4.0) is not supported with python2.7. The last supported was version 3.4.
`pip install 'ftputil==3.4'`
