### ISSUE TITLE
Can't export large schematic (MCEdit hangs)

### ISSUE THREAD

**Issue by allamassal** [Khroki/MCEdit-Unified#841]
So I just tried to export a schematic that was about 100 blocks on both sides, and then MCEdit stopped responding. I went into Task Manager and noticed the memory usage by MCEdit was rapidly increasing, and was over a gigabyte by the time I killed the process. This only happens in the latest version of MCEdit.

**Comment by LaChal** [comment]
Did you selected the schematic format in the file dialog?

By default, the file dialog wants to use the NBT format, which can require a large amount of RAM since the data can't be 'sliced' to be written on the disk...

Depending on the MCEdit internal block buffer setting in the `Options` panel, MCEdit will create a raw schematic file or a zipped one.

**Comment by allamassal** [comment]
You're right. I was trying to use the NBT format.
