### ISSUE TITLE
1.2 World Format Changed

### ISSUE THREAD

**Issue by neonerz** [Khroki/MCEdit-Unified#842]
The LevelDB format changed a bit causing mcedit to be unable to read 1.2 worlds.

The changes were published on Mojang's github here: https://github.com/Mojang/leveldb-mcpe

Attached is a 1.2 world using the latest beta as an example.

[1.2 Test World.mcworld.zip](https://github.com/Khroki/MCEdit-Unified/files/1250725/1.2.Test.World.mcworld.zip)

**Comment by neonerz** [comment]
That test world I gave isn't a good example. Here's a new world generated in 1.2 and I placed some blocks.

Also included is a compiled DLL from the PE version of [MCCToolChest ](http://mcctoolchest.com/Download) for the new leveldb format (64bit version). If I use this DLL, when I load the map it gives an error about the chunks being empty, but if I ignore the error, it loads up the world. I then did a quick fill replace, saved it, and opened it back up in 1.2 and the changes in MCEdit worked.

So the questions are:

1. why does mcedit complain about the chunks being empty, but successfully load the map?
1. Is there anything else broken?

[Testing 1.2 Crash.mcworld.zip](https://github.com/Khroki/MCEdit-Unified/files/1253050/Testing.1.2.Crash.mcworld.zip)

[LevelDB-MCPE.zip](https://github.com/Khroki/MCEdit-Unified/files/1253051/LevelDB-MCPE.zip) (64bit DLL file zipped up since github doesn't allow them to be uploaded)

**Comment by LaChal** [comment]
I guess we won't use this DLL because we don't know which commit on Mojang's repo was used and we don't know how it was compiled.

Regarding the world you sent in your second message, here is what I see when I open it in the current dev MCEdit (on Linux and Windows):
![2017-09-02 03-06-44-](https://user-images.githubusercontent.com/7809746/29995722-64639502-8ff0-11e7-9eb7-1d0ad85f0f9c.png)
![2017-09-02 03-07-56-](https://user-images.githubusercontent.com/7809746/29995724-8b2e5bea-8ff0-11e7-8875-b553477e4a83.png)

Filling a random area in an existing chunk with stone also worked. But I could not verify this in game...

**Comment by bman92102** [comment]
I tested with a 1.2 world and the set biome filter doesn't work anymore. I can't give the exact error currently, but if you attempt to change the biome on the 1.2 worlds, it gives an error on the amount of arguments given.

**Comment by LaChal** [comment]
The cause of the 'create chunk' bug has been found. This may also cause the biome filter error.

**Comment by bman92102** [comment]
That's why I removed my comment, worked on some world's, so I thought it was just me :smile:

**Comment by neonerz** [comment]
Can confirm this is working now. A newer version of LevelDB-MCPE.dll than what comes with source is required, but I no longer get the 'create chunk' bug.

**Comment by CarJem** [comment]
Any chance that this is still being looked at?

**Comment by LaChal** [comment]
We're looking to this.

A new version of the binary support will be provided once we could rebuild and test it.

**Comment by Podshot** [comment]
We think we've successfully added support for the new world format, we're currently testing all of the maps we can to make sure

**Comment by naor2013** [comment]
Not sure why it's still open if everything works now... Newer LevelDB-MCPE does not mean supporting the newer version since LevelDB is the code that knows to read the type of file, not the MCPE format. They probably fixed issues that they had with the phone support for the type of file so updating it does not mean better support for the new format and if we'll decide it's needed, we'll do it. If you still have issues like the "Create chunk" ones, we'd love if you could report those, we really try to fix them as quickly as we can and hope we'll soon have the new release out with MCPE support :)
