### ISSUE TITLE
level.gameVersion bug/suggestion

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#849]
level.gameVersion is a bit inconsistent in its output across the different versions. In bedrock and schematic it returns "PE" and "Schematic" respectively. With the PC version it returns the game version number (eg "1.12.1"). This makes it quite hard to tell definitively if a world is a java world. I don't know what the expected behaviour of this is but can it be made consistent?

Ideally there should be two different attributes. One for which platform version it is from ("Java", "Schematic", "PE"...) and another for game version like the java one currently is

**Comment by Podshot** [comment]
I'll try my best to implement something similar to this. The only problem is that only the Java edition seems to store it's numerical version (IE: 1.12 or the internal version ID), so our best version detection for everything else is just whether it is a PE/Schematic. I'll implement a `level.gamePlatform` (IE: Java, PE, Schematic) that'll be return the 'edition' the world it, then level.gameVersion will either be the Java version or the same thing returned by `level.gamePlatform`. Does that (mostly) meet your suggestion?

**Comment by gentlegiantJGC** [comment]
Yeh that's brilliant thanks

**Comment by LaChal** [comment]
Right, only PC (Java) worlds contains a version string like '1.2.3' since approx MC 1.9, so, difference between 1.6 and 1.7 worlds can't be really done...

PE worlds store a single byte at the very beginning of the level.dat file which seem reflects the leveldb compatibility more than the game version itself.
For now, we can only assert the byte numerical values over than 4 are used in PE 1+ game versions.
A value equal or higher than 6 is used by PE 1.2 (and maybe over).

**Comment by gentlegiantJGC** [comment]
@LaChal just gone digging through the level.dat file for bedrock and the version the world was last opened in is stored in there.
```
  "lastOpenedWithVersion": TAG_List([
    TAG_Int(1),
    TAG_Int(1),
    TAG_Int(5),
    TAG_Int(0),
  ]),
```

**Comment by LaChal** [comment]
Interesting, indeed.

But I suppose it is the game version, not the world one.
To properly open and save the world, its version is needed.

Anyway, this need to be dug more :smile:
