### ISSUE TITLE
Mcedit UnicodeEncodeError('ascii', error code

### ISSUE THREAD

**Issue by DamnedCyborg** [Khroki/MCEdit-Unified#861]
Little problem while trying to open a level.dat file (from a mcpe map) with mcedit, i've got this error code...
I'm trying to save a friend's map (which doesn't want to work AT ALL, like, i'm juste launching it on mcpe, and then, the game crashes... EVERY-FUCKIN'-TIME (sorry but i'm a little bit angry after trying to restore this for something like 3 hours)
The other problem is when i'm trying to launch the file chunks.dat. Nothing happens. Just, nothing.
Can anyone help me? I'm tired of this problem and can't fix it by myself .-. (sorry if i did some mistakes, but i'm still learning english x')

**Comment by Podshot** [comment]
Can you give us a screenshot of the console window and the complete error?

**Comment by DamnedCyborg** [comment]
![error 2](https://user-images.githubusercontent.com/33106230/32106604-6a9fbb0a-bb2c-11e7-8576-2595108a8a61.jpg)
![error](https://user-images.githubusercontent.com/33106230/32106605-6ab9c2a2-bb2c-11e7-94bb-a07c456d89b1.jpg)
Here they are ^^

**Comment by naor2013** [comment]
Seems like you're running 1.5.6.0 which is still not fully ready for MCPE maps. We fixed this issue for the next release (1.6.0.0) but it can take time for it to be released since we have a lot of issues to fix there and we don't have too much time to work on MCEdit. For this, we make weekly pre-releases that you can test but still have all the bugs we're fixing at the moment, so you can use it to edit MCPE maps but we advise you to have a backup of your map before using it since it's not stable and may break your map. You can find those releases here: https://github.com/Podshot/MCEdit-Unified-Preview/releases
Just remember to backup your maps before using and we'd love if you could report any bugs you experience with those releases :)
